# Generated by Django 3.2.9 on 2022-01-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('default_country', models.CharField(blank=True, max_length=30, null=True)),
                ('default_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('default_town_city', models.CharField(blank=True, max_length=30, null=True)),
                ('default_address_1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address_2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address_3', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
