# Generated by Django 3.2.9 on 2022-01-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_profile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_id',
        ),
    ]
