# Generated by Django 3.2.9 on 2022-01-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_remove_profile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
