# Generated by Django 3.2.9 on 2022-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_restricted',
            field=models.BooleanField(default=True),
        ),
    ]
