# Generated by Django 3.2.9 on 2022-01-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0003_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
