# Generated by Django 3.2.9 on 2022-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0004_remove_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='this_is_a_slugfield'),
        ),
        migrations.AddField(
            model_name='article',
            name='teaser',
            field=models.TextField(default='this is a teaser field.', max_length=250),
        ),
    ]
