# Generated by Django 3.2.9 on 2022-01-14 14:25

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0005_auto_20220114_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'id']),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
