# Generated by Django 3.2.9 on 2022-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0006_auto_20220114_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
