# Generated by Django 3.2.9 on 2022-01-16 22:07

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article_page', '0007_alter_article_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
