# Generated by Django 3.2.9 on 2022-01-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20220130_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='subscriptions.subscriptionproduct'),
        ),
    ]
