# Generated by Django 3.2.9 on 2022-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_sub_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Cancelled'), ('none', 'None'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='incomplete', max_length=25),
        ),
    ]
