# Generated by Django 3.2.9 on 2022-01-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_profile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
