# Generated by Django 3.2.9 on 2022-01-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_delete_subscriber'),
        ('user_profiles', '0005_auto_20220128_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_billing_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(choices=[('curr', 'Current'), ('pstd', 'Past Due'), ('cncl', 'Cancelled'), ('none', 'None')], default='none', max_length=4),
        ),
    ]
