# Generated by Django 3.2.9 on 2022-01-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20220129_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_last_payment_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_next_payment_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_payment_start_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_billing_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_status',
        ),
    ]
