# Generated by Django 3.2.9 on 2022-01-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberclass',
            name='subscriber_status',
        ),
        migrations.RemoveField(
            model_name='subscriberclass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='SubscriberClass',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
